name: Python CI Workflow

on:
  push:
    branches:
      - main  # Trigger on push to main
  pull_request:
    branches:
      - main  # Trigger on pull request to main

jobs:
  test:
    strategy:
      matrix:
        python-version: [3.8, 3.9]  # Test only Python 3.8 and 3.9
        os: [ubuntu-latest, windows-latest, macos-latest]  # Different OS

    runs-on: ${{ matrix.os }}  # The OS will be selected from the matrix

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the repository's code

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4  # Set up Python version
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt || echo "No requirements.txt file"  # Install dependencies (if any)

      - name: Show Python version and OS
        run: |
          echo "Running on OS: ${{ matrix.os }}"
          python --version  # Check Python version

      - name: Run main.py on Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}  # Run only on Ubuntu
        run: |
          echo "Running on Ubuntu!"
          python main.py  # Execute your main.py script

      - name: Run main.py on Windows
        if: ${{ matrix.os == 'windows-latest' }}  # Run only on Windows
        run: |
          echo "Running on Windows!"
          python main.py  # Execute your main.py script

      - name: Run main.py on macOS
        if: ${{ matrix.os == 'macos-latest' }}  # Run only on macOS
        run: |
          echo "Running on macOS!"
          python main.py  # Execute your main.py script

      - name: Conditional Step: Check if requirements.txt exists
        run: |
          if [ -f requirements.txt ]; then
            echo "requirements.txt file found, installing dependencies!"
            pip install -r requirements.txt
          else
            echo "No requirements.txt file found, skipping dependency installation!"
          fi
